# Use postgres/example user/password credentials
version: '3.2'

services:

  db:
    image: postgres
    container_name: go_mux_restapi_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pgsql_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

  adminer:
    container_name: go_mux_restapi_adminer
    image: adminer
    restart: always
    ports:
      - 6789:8080
  api:
    image: phuoc/go-mux-restapi:v1.0.1
    container_name: go_mux_restapi_api
    ports:
      - 7575:8080
    environment:
      PORT: "8080"
      APP_DB_USERNAME: admin
      APP_DB_PASSWORD: 123456
      APP_DB_NAME: test
      APP_DB_HOST: db
      APP_DB_PORT: 5432
    links:
      - db
volumes:
  pgsql_data: