apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "test"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "123456"
  PGDATA: "/var/lib/postgresql/data/pgdata"